// Code generated by MockGen. DO NOT EDIT.
// Source: user-api/internal/service (interfaces: UserService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks user-api/internal/service UserService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "user-api/internal/domain"
	service "user-api/internal/service"

	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetUserPreferences mocks base method.
func (m *MockUserService) GetUserPreferences(ctx context.Context, userID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPreferences", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPreferences indicates an expected call of GetUserPreferences.
func (mr *MockUserServiceMockRecorder) GetUserPreferences(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPreferences", reflect.TypeOf((*MockUserService)(nil).GetUserPreferences), ctx, userID)
}

// ListSupportedCurrencies mocks base method.
func (m *MockUserService) ListSupportedCurrencies(ctx context.Context) ([]domain.CurrencyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSupportedCurrencies", ctx)
	ret0, _ := ret[0].([]domain.CurrencyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSupportedCurrencies indicates an expected call of ListSupportedCurrencies.
func (mr *MockUserServiceMockRecorder) ListSupportedCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSupportedCurrencies", reflect.TypeOf((*MockUserService)(nil).ListSupportedCurrencies), ctx)
}

// UpdateUserPreferences mocks base method.
func (m *MockUserService) UpdateUserPreferences(ctx context.Context, input service.UpdatePreferencesInput) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPreferences", ctx, input)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPreferences indicates an expected call of UpdateUserPreferences.
func (mr *MockUserServiceMockRecorder) UpdateUserPreferences(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPreferences", reflect.TypeOf((*MockUserService)(nil).UpdateUserPreferences), ctx, input)
}
