// Code generated by MockGen. DO NOT EDIT.
// Source: portfolio-api/internal/repository (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks portfolio-api/internal/repository Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "portfolio-api/internal/domain"
	marketdata "portfolio-api/internal/marketdata"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BatchUpsertFXRates mocks base method.
func (m *MockRepository) BatchUpsertFXRates(ctx context.Context, records []marketdata.FXRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpsertFXRates", ctx, records)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpsertFXRates indicates an expected call of BatchUpsertFXRates.
func (mr *MockRepositoryMockRecorder) BatchUpsertFXRates(ctx, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsertFXRates", reflect.TypeOf((*MockRepository)(nil).BatchUpsertFXRates), ctx, records)
}

// BatchUpsertInstrumentPrices mocks base method.
func (m *MockRepository) BatchUpsertInstrumentPrices(ctx context.Context, records []marketdata.PriceRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpsertInstrumentPrices", ctx, records)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpsertInstrumentPrices indicates an expected call of BatchUpsertInstrumentPrices.
func (mr *MockRepositoryMockRecorder) BatchUpsertInstrumentPrices(ctx, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsertInstrumentPrices", reflect.TypeOf((*MockRepository)(nil).BatchUpsertInstrumentPrices), ctx, records)
}

// CreateInstrument mocks base method.
func (m *MockRepository) CreateInstrument(ctx context.Context, input domain.CreateInstrumentInput) (*domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstrument", ctx, input)
	ret0, _ := ret[0].(*domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstrument indicates an expected call of CreateInstrument.
func (mr *MockRepositoryMockRecorder) CreateInstrument(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstrument", reflect.TypeOf((*MockRepository)(nil).CreateInstrument), ctx, input)
}

// DeleteTransaction mocks base method.
func (m *MockRepository) DeleteTransaction(ctx context.Context, portfolioID, transactionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", ctx, portfolioID, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockRepositoryMockRecorder) DeleteTransaction(ctx, portfolioID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockRepository)(nil).DeleteTransaction), ctx, portfolioID, transactionID)
}

// DeleteValuationsFromDate mocks base method.
func (m *MockRepository) DeleteValuationsFromDate(ctx context.Context, portfolioID uuid.UUID, fromDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteValuationsFromDate", ctx, portfolioID, fromDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteValuationsFromDate indicates an expected call of DeleteValuationsFromDate.
func (mr *MockRepositoryMockRecorder) DeleteValuationsFromDate(ctx, portfolioID, fromDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteValuationsFromDate", reflect.TypeOf((*MockRepository)(nil).DeleteValuationsFromDate), ctx, portfolioID, fromDate)
}

// FindInstrumentBySymbol mocks base method.
func (m *MockRepository) FindInstrumentBySymbol(ctx context.Context, symbol string) (*domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInstrumentBySymbol", ctx, symbol)
	ret0, _ := ret[0].(*domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInstrumentBySymbol indicates an expected call of FindInstrumentBySymbol.
func (mr *MockRepositoryMockRecorder) FindInstrumentBySymbol(ctx, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInstrumentBySymbol", reflect.TypeOf((*MockRepository)(nil).FindInstrumentBySymbol), ctx, symbol)
}

// FindPortfolioByUser mocks base method.
func (m *MockRepository) FindPortfolioByUser(ctx context.Context, userID string) (*domain.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPortfolioByUser", ctx, userID)
	ret0, _ := ret[0].(*domain.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPortfolioByUser indicates an expected call of FindPortfolioByUser.
func (mr *MockRepositoryMockRecorder) FindPortfolioByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPortfolioByUser", reflect.TypeOf((*MockRepository)(nil).FindPortfolioByUser), ctx, userID)
}

// FindPortfoliosHoldingInstrument mocks base method.
func (m *MockRepository) FindPortfoliosHoldingInstrument(ctx context.Context, instrumentID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPortfoliosHoldingInstrument", ctx, instrumentID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPortfoliosHoldingInstrument indicates an expected call of FindPortfoliosHoldingInstrument.
func (mr *MockRepositoryMockRecorder) FindPortfoliosHoldingInstrument(ctx, instrumentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPortfoliosHoldingInstrument", reflect.TypeOf((*MockRepository)(nil).FindPortfoliosHoldingInstrument), ctx, instrumentID)
}

// GetCashBalances mocks base method.
func (m *MockRepository) GetCashBalances(ctx context.Context, portfolioID uuid.UUID) ([]domain.CashBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCashBalances", ctx, portfolioID)
	ret0, _ := ret[0].([]domain.CashBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCashBalances indicates an expected call of GetCashBalances.
func (mr *MockRepositoryMockRecorder) GetCashBalances(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCashBalances", reflect.TypeOf((*MockRepository)(nil).GetCashBalances), ctx, portfolioID)
}

// GetCashFXRates mocks base method.
func (m *MockRepository) GetCashFXRates(ctx context.Context, baseCurrency string) (map[string]decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCashFXRates", ctx, baseCurrency)
	ret0, _ := ret[0].(map[string]decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCashFXRates indicates an expected call of GetCashFXRates.
func (mr *MockRepositoryMockRecorder) GetCashFXRates(ctx, baseCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCashFXRates", reflect.TypeOf((*MockRepository)(nil).GetCashFXRates), ctx, baseCurrency)
}

// GetCorporateActions mocks base method.
func (m *MockRepository) GetCorporateActions(ctx context.Context, instrumentIDs []uuid.UUID) ([]domain.CorporateAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorporateActions", ctx, instrumentIDs)
	ret0, _ := ret[0].([]domain.CorporateAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCorporateActions indicates an expected call of GetCorporateActions.
func (mr *MockRepositoryMockRecorder) GetCorporateActions(ctx, instrumentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorporateActions", reflect.TypeOf((*MockRepository)(nil).GetCorporateActions), ctx, instrumentIDs)
}

// GetFXRate mocks base method.
func (m *MockRepository) GetFXRate(ctx context.Context, fromCurrency, toCurrency string) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFXRate", ctx, fromCurrency, toCurrency)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFXRate indicates an expected call of GetFXRate.
func (mr *MockRepositoryMockRecorder) GetFXRate(ctx, fromCurrency, toCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFXRate", reflect.TypeOf((*MockRepository)(nil).GetFXRate), ctx, fromCurrency, toCurrency)
}

// GetHistoricalFXMatrix mocks base method.
func (m *MockRepository) GetHistoricalFXMatrix(ctx context.Context, currencies []string, baseCurrency string, fromDate, toDate time.Time) (map[string]map[string]decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoricalFXMatrix", ctx, currencies, baseCurrency, fromDate, toDate)
	ret0, _ := ret[0].(map[string]map[string]decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoricalFXMatrix indicates an expected call of GetHistoricalFXMatrix.
func (mr *MockRepositoryMockRecorder) GetHistoricalFXMatrix(ctx, currencies, baseCurrency, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoricalFXMatrix", reflect.TypeOf((*MockRepository)(nil).GetHistoricalFXMatrix), ctx, currencies, baseCurrency, fromDate, toDate)
}

// GetHistoricalFXRates mocks base method.
func (m *MockRepository) GetHistoricalFXRates(ctx context.Context, baseCurrency, quoteCurrency string, fromDate, toDate *time.Time) ([]domain.FXRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoricalFXRates", ctx, baseCurrency, quoteCurrency, fromDate, toDate)
	ret0, _ := ret[0].([]domain.FXRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoricalFXRates indicates an expected call of GetHistoricalFXRates.
func (mr *MockRepositoryMockRecorder) GetHistoricalFXRates(ctx, baseCurrency, quoteCurrency, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoricalFXRates", reflect.TypeOf((*MockRepository)(nil).GetHistoricalFXRates), ctx, baseCurrency, quoteCurrency, fromDate, toDate)
}

// GetHistoricalPriceMatrix mocks base method.
func (m *MockRepository) GetHistoricalPriceMatrix(ctx context.Context, instrumentIDs []uuid.UUID, fromDate, toDate time.Time) (map[uuid.UUID]map[string]decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoricalPriceMatrix", ctx, instrumentIDs, fromDate, toDate)
	ret0, _ := ret[0].(map[uuid.UUID]map[string]decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoricalPriceMatrix indicates an expected call of GetHistoricalPriceMatrix.
func (mr *MockRepositoryMockRecorder) GetHistoricalPriceMatrix(ctx, instrumentIDs, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoricalPriceMatrix", reflect.TypeOf((*MockRepository)(nil).GetHistoricalPriceMatrix), ctx, instrumentIDs, fromDate, toDate)
}

// GetHoldingsWithMarketData mocks base method.
func (m *MockRepository) GetHoldingsWithMarketData(ctx context.Context, portfolioID uuid.UUID) ([]domain.HoldingWithPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHoldingsWithMarketData", ctx, portfolioID)
	ret0, _ := ret[0].([]domain.HoldingWithPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHoldingsWithMarketData indicates an expected call of GetHoldingsWithMarketData.
func (mr *MockRepositoryMockRecorder) GetHoldingsWithMarketData(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHoldingsWithMarketData", reflect.TypeOf((*MockRepository)(nil).GetHoldingsWithMarketData), ctx, portfolioID)
}

// GetIngestionMetrics mocks base method.
func (m *MockRepository) GetIngestionMetrics(ctx context.Context) (*domain.IngestionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngestionMetrics", ctx)
	ret0, _ := ret[0].(*domain.IngestionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIngestionMetrics indicates an expected call of GetIngestionMetrics.
func (mr *MockRepositoryMockRecorder) GetIngestionMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngestionMetrics", reflect.TypeOf((*MockRepository)(nil).GetIngestionMetrics), ctx)
}

// GetLatestValuation mocks base method.
func (m *MockRepository) GetLatestValuation(ctx context.Context, portfolioID uuid.UUID) (*domain.PortfolioValuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValuation", ctx, portfolioID)
	ret0, _ := ret[0].(*domain.PortfolioValuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValuation indicates an expected call of GetLatestValuation.
func (mr *MockRepositoryMockRecorder) GetLatestValuation(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValuation", reflect.TypeOf((*MockRepository)(nil).GetLatestValuation), ctx, portfolioID)
}

// GetLatestValuationBefore mocks base method.
func (m *MockRepository) GetLatestValuationBefore(ctx context.Context, portfolioID uuid.UUID, beforeDate time.Time) (*domain.PortfolioValuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValuationBefore", ctx, portfolioID, beforeDate)
	ret0, _ := ret[0].(*domain.PortfolioValuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValuationBefore indicates an expected call of GetLatestValuationBefore.
func (mr *MockRepositoryMockRecorder) GetLatestValuationBefore(ctx, portfolioID, beforeDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValuationBefore", reflect.TypeOf((*MockRepository)(nil).GetLatestValuationBefore), ctx, portfolioID, beforeDate)
}

// GetPortfolioValuations mocks base method.
func (m *MockRepository) GetPortfolioValuations(ctx context.Context, portfolioID uuid.UUID, fromDate time.Time) ([]domain.PortfolioValuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolioValuations", ctx, portfolioID, fromDate)
	ret0, _ := ret[0].([]domain.PortfolioValuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPortfolioValuations indicates an expected call of GetPortfolioValuations.
func (mr *MockRepositoryMockRecorder) GetPortfolioValuations(ctx, portfolioID, fromDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolioValuations", reflect.TypeOf((*MockRepository)(nil).GetPortfolioValuations), ctx, portfolioID, fromDate)
}

// GetTransactions mocks base method.
func (m *MockRepository) GetTransactions(ctx context.Context, portfolioID uuid.UUID) ([]domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, portfolioID)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockRepositoryMockRecorder) GetTransactions(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockRepository)(nil).GetTransactions), ctx, portfolioID)
}

// HasPricesForRange mocks base method.
func (m *MockRepository) HasPricesForRange(ctx context.Context, instrumentID uuid.UUID, fromDate, toDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPricesForRange", ctx, instrumentID, fromDate, toDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPricesForRange indicates an expected call of HasPricesForRange.
func (mr *MockRepositoryMockRecorder) HasPricesForRange(ctx, instrumentID, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPricesForRange", reflect.TypeOf((*MockRepository)(nil).HasPricesForRange), ctx, instrumentID, fromDate, toDate)
}

// InsertTransaction mocks base method.
func (m *MockRepository) InsertTransaction(ctx context.Context, tx domain.Transaction) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransaction", ctx, tx)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTransaction indicates an expected call of InsertTransaction.
func (mr *MockRepositoryMockRecorder) InsertTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransaction", reflect.TypeOf((*MockRepository)(nil).InsertTransaction), ctx, tx)
}

// ListActiveCurrencies mocks base method.
func (m *MockRepository) ListActiveCurrencies(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveCurrencies", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveCurrencies indicates an expected call of ListActiveCurrencies.
func (mr *MockRepositoryMockRecorder) ListActiveCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveCurrencies", reflect.TypeOf((*MockRepository)(nil).ListActiveCurrencies), ctx)
}

// ListActiveInstruments mocks base method.
func (m *MockRepository) ListActiveInstruments(ctx context.Context) ([]domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveInstruments", ctx)
	ret0, _ := ret[0].([]domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveInstruments indicates an expected call of ListActiveInstruments.
func (mr *MockRepositoryMockRecorder) ListActiveInstruments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveInstruments", reflect.TypeOf((*MockRepository)(nil).ListActiveInstruments), ctx)
}

// ListActivePortfolios mocks base method.
func (m *MockRepository) ListActivePortfolios(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivePortfolios", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActivePortfolios indicates an expected call of ListActivePortfolios.
func (mr *MockRepositoryMockRecorder) ListActivePortfolios(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivePortfolios", reflect.TypeOf((*MockRepository)(nil).ListActivePortfolios), ctx)
}

// ListAllInstruments mocks base method.
func (m *MockRepository) ListAllInstruments(ctx context.Context, isActive *bool, search *string) ([]domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllInstruments", ctx, isActive, search)
	ret0, _ := ret[0].([]domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllInstruments indicates an expected call of ListAllInstruments.
func (mr *MockRepositoryMockRecorder) ListAllInstruments(ctx, isActive, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllInstruments", reflect.TypeOf((*MockRepository)(nil).ListAllInstruments), ctx, isActive, search)
}

// ListCurrencyPairs mocks base method.
func (m *MockRepository) ListCurrencyPairs(ctx context.Context) ([]domain.CurrencyPairSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCurrencyPairs", ctx)
	ret0, _ := ret[0].([]domain.CurrencyPairSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCurrencyPairs indicates an expected call of ListCurrencyPairs.
func (mr *MockRepositoryMockRecorder) ListCurrencyPairs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCurrencyPairs", reflect.TypeOf((*MockRepository)(nil).ListCurrencyPairs), ctx)
}

// ListFXRates mocks base method.
func (m *MockRepository) ListFXRates(ctx context.Context, filter domain.FXRateFilter) ([]domain.FXRate, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFXRates", ctx, filter)
	ret0, _ := ret[0].([]domain.FXRate)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFXRates indicates an expected call of ListFXRates.
func (mr *MockRepositoryMockRecorder) ListFXRates(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFXRates", reflect.TypeOf((*MockRepository)(nil).ListFXRates), ctx, filter)
}

// ListInstrumentPrices mocks base method.
func (m *MockRepository) ListInstrumentPrices(ctx context.Context, filter domain.PriceFilter) ([]domain.InstrumentPrice, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstrumentPrices", ctx, filter)
	ret0, _ := ret[0].([]domain.InstrumentPrice)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInstrumentPrices indicates an expected call of ListInstrumentPrices.
func (mr *MockRepositoryMockRecorder) ListInstrumentPrices(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstrumentPrices", reflect.TypeOf((*MockRepository)(nil).ListInstrumentPrices), ctx, filter)
}

// ListTransactions mocks base method.
func (m *MockRepository) ListTransactions(ctx context.Context, portfolioID uuid.UUID, filter domain.TransactionFilter) ([]domain.TransactionWithInstrument, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, portfolioID, filter)
	ret0, _ := ret[0].([]domain.TransactionWithInstrument)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockRepositoryMockRecorder) ListTransactions(ctx, portfolioID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockRepository)(nil).ListTransactions), ctx, portfolioID, filter)
}

// SaveProjectionsTx mocks base method.
func (m *MockRepository) SaveProjectionsTx(ctx context.Context, portfolioID uuid.UUID, lots []domain.TaxLot, disposals []domain.LotDisposal, holdings []domain.Holding, cash []domain.CashBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProjectionsTx", ctx, portfolioID, lots, disposals, holdings, cash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveProjectionsTx indicates an expected call of SaveProjectionsTx.
func (mr *MockRepositoryMockRecorder) SaveProjectionsTx(ctx, portfolioID, lots, disposals, holdings, cash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProjectionsTx", reflect.TypeOf((*MockRepository)(nil).SaveProjectionsTx), ctx, portfolioID, lots, disposals, holdings, cash)
}

// UpdateInstrument mocks base method.
func (m *MockRepository) UpdateInstrument(ctx context.Context, input domain.UpdateInstrumentInput) (*domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstrument", ctx, input)
	ret0, _ := ret[0].(*domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstrument indicates an expected call of UpdateInstrument.
func (mr *MockRepositoryMockRecorder) UpdateInstrument(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstrument", reflect.TypeOf((*MockRepository)(nil).UpdateInstrument), ctx, input)
}

// UpdatePortfolioBaseCurrency mocks base method.
func (m *MockRepository) UpdatePortfolioBaseCurrency(ctx context.Context, portfolioID uuid.UUID, baseCurrency string, fxRate decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePortfolioBaseCurrency", ctx, portfolioID, baseCurrency, fxRate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePortfolioBaseCurrency indicates an expected call of UpdatePortfolioBaseCurrency.
func (mr *MockRepositoryMockRecorder) UpdatePortfolioBaseCurrency(ctx, portfolioID, baseCurrency, fxRate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePortfolioBaseCurrency", reflect.TypeOf((*MockRepository)(nil).UpdatePortfolioBaseCurrency), ctx, portfolioID, baseCurrency, fxRate)
}

// UpsertFXRate mocks base method.
func (m *MockRepository) UpsertFXRate(ctx context.Context, baseCurrency, quoteCurrency string, rateDate time.Time, rate decimal.Decimal, source string) (*domain.FXRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFXRate", ctx, baseCurrency, quoteCurrency, rateDate, rate, source)
	ret0, _ := ret[0].(*domain.FXRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertFXRate indicates an expected call of UpsertFXRate.
func (mr *MockRepositoryMockRecorder) UpsertFXRate(ctx, baseCurrency, quoteCurrency, rateDate, rate, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFXRate", reflect.TypeOf((*MockRepository)(nil).UpsertFXRate), ctx, baseCurrency, quoteCurrency, rateDate, rate, source)
}

// UpsertInstrumentPrice mocks base method.
func (m *MockRepository) UpsertInstrumentPrice(ctx context.Context, instrumentID uuid.UUID, priceDate time.Time, closePrice decimal.Decimal, source string) (*domain.InstrumentPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertInstrumentPrice", ctx, instrumentID, priceDate, closePrice, source)
	ret0, _ := ret[0].(*domain.InstrumentPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertInstrumentPrice indicates an expected call of UpsertInstrumentPrice.
func (mr *MockRepositoryMockRecorder) UpsertInstrumentPrice(ctx, instrumentID, priceDate, closePrice, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertInstrumentPrice", reflect.TypeOf((*MockRepository)(nil).UpsertInstrumentPrice), ctx, instrumentID, priceDate, closePrice, source)
}

// UpsertValuationsBatch mocks base method.
func (m *MockRepository) UpsertValuationsBatch(ctx context.Context, valuations []domain.PortfolioValuation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertValuationsBatch", ctx, valuations)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertValuationsBatch indicates an expected call of UpsertValuationsBatch.
func (mr *MockRepositoryMockRecorder) UpsertValuationsBatch(ctx, valuations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertValuationsBatch", reflect.TypeOf((*MockRepository)(nil).UpsertValuationsBatch), ctx, valuations)
}
