// Code generated by MockGen. DO NOT EDIT.
// Source: portfolio-api/internal/repository (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks portfolio-api/internal/repository Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "portfolio-api/internal/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindPortfolioByUser mocks base method.
func (m *MockRepository) FindPortfolioByUser(ctx context.Context, userID string) (*domain.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPortfolioByUser", ctx, userID)
	ret0, _ := ret[0].(*domain.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPortfolioByUser indicates an expected call of FindPortfolioByUser.
func (mr *MockRepositoryMockRecorder) FindPortfolioByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPortfolioByUser", reflect.TypeOf((*MockRepository)(nil).FindPortfolioByUser), ctx, userID)
}

// GetCashBalances mocks base method.
func (m *MockRepository) GetCashBalances(ctx context.Context, portfolioID uuid.UUID) ([]domain.CashBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCashBalances", ctx, portfolioID)
	ret0, _ := ret[0].([]domain.CashBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCashBalances indicates an expected call of GetCashBalances.
func (mr *MockRepositoryMockRecorder) GetCashBalances(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCashBalances", reflect.TypeOf((*MockRepository)(nil).GetCashBalances), ctx, portfolioID)
}

// GetCashFXRates mocks base method.
func (m *MockRepository) GetCashFXRates(ctx context.Context, baseCurrency string) (map[string]decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCashFXRates", ctx, baseCurrency)
	ret0, _ := ret[0].(map[string]decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCashFXRates indicates an expected call of GetCashFXRates.
func (mr *MockRepositoryMockRecorder) GetCashFXRates(ctx, baseCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCashFXRates", reflect.TypeOf((*MockRepository)(nil).GetCashFXRates), ctx, baseCurrency)
}

// GetCorporateActions mocks base method.
func (m *MockRepository) GetCorporateActions(ctx context.Context, instrumentIDs []uuid.UUID) ([]domain.CorporateAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorporateActions", ctx, instrumentIDs)
	ret0, _ := ret[0].([]domain.CorporateAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCorporateActions indicates an expected call of GetCorporateActions.
func (mr *MockRepositoryMockRecorder) GetCorporateActions(ctx, instrumentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorporateActions", reflect.TypeOf((*MockRepository)(nil).GetCorporateActions), ctx, instrumentIDs)
}

// GetHoldingsWithMarketData mocks base method.
func (m *MockRepository) GetHoldingsWithMarketData(ctx context.Context, portfolioID uuid.UUID) ([]domain.HoldingWithPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHoldingsWithMarketData", ctx, portfolioID)
	ret0, _ := ret[0].([]domain.HoldingWithPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHoldingsWithMarketData indicates an expected call of GetHoldingsWithMarketData.
func (mr *MockRepositoryMockRecorder) GetHoldingsWithMarketData(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHoldingsWithMarketData", reflect.TypeOf((*MockRepository)(nil).GetHoldingsWithMarketData), ctx, portfolioID)
}

// GetLatestValuation mocks base method.
func (m *MockRepository) GetLatestValuation(ctx context.Context, portfolioID uuid.UUID) (*domain.PortfolioValuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValuation", ctx, portfolioID)
	ret0, _ := ret[0].(*domain.PortfolioValuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValuation indicates an expected call of GetLatestValuation.
func (mr *MockRepositoryMockRecorder) GetLatestValuation(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValuation", reflect.TypeOf((*MockRepository)(nil).GetLatestValuation), ctx, portfolioID)
}

// GetTransactions mocks base method.
func (m *MockRepository) GetTransactions(ctx context.Context, portfolioID uuid.UUID) ([]domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, portfolioID)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockRepositoryMockRecorder) GetTransactions(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockRepository)(nil).GetTransactions), ctx, portfolioID)
}

// SaveProjectionsTx mocks base method.
func (m *MockRepository) SaveProjectionsTx(ctx context.Context, portfolioID uuid.UUID, lots []domain.TaxLot, disposals []domain.LotDisposal, holdings []domain.Holding, cash []domain.CashBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProjectionsTx", ctx, portfolioID, lots, disposals, holdings, cash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveProjectionsTx indicates an expected call of SaveProjectionsTx.
func (mr *MockRepositoryMockRecorder) SaveProjectionsTx(ctx, portfolioID, lots, disposals, holdings, cash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProjectionsTx", reflect.TypeOf((*MockRepository)(nil).SaveProjectionsTx), ctx, portfolioID, lots, disposals, holdings, cash)
}
