syntax = "proto3";

package portfolio.v1;

import "common/v1/decimal.proto";

option go_package = "graphfolio/proto/portfolio/v1;portfoliopb";

service PortfolioService {
  rpc GetPortfolio(GetPortfolioRequest) returns (GetPortfolioResponse) {}
}

message GetPortfolioRequest {
  string user_id = 1;
}

message GetPortfolioResponse {
  Portfolio portfolio = 1;
}

message Portfolio {
  common.v1.Money   total_value               = 1;
  common.v1.Money   today_return_amount       = 2;
  common.v1.Decimal today_return_percent      = 3;
  common.v1.Decimal annualized_return_percent = 4;
  common.v1.Money   cash_balance              = 5;
  repeated Investment investments             = 6;
}

message Investment {
  string            id                   = 1;
  string            ticker               = 2;
  string            name                 = 3;
  common.v1.Money   price                = 4;
  common.v1.Decimal quantity             = 5;
  common.v1.Money   total_value          = 6;
  common.v1.Money   today_return_amount  = 7;
  common.v1.Decimal today_return_percent = 8;
  common.v1.Money   total_return_amount  = 9;
  common.v1.Decimal total_return_percent = 10;
}
