// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.1
// source: portfolio/v1/portfolio.proto

package portfoliopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PortfolioService_GetPortfolio_FullMethodName                = "/portfolio.v1.PortfolioService/GetPortfolio"
	PortfolioService_UpdatePortfolioBaseCurrency_FullMethodName = "/portfolio.v1.PortfolioService/UpdatePortfolioBaseCurrency"
	PortfolioService_AddTransaction_FullMethodName              = "/portfolio.v1.PortfolioService/AddTransaction"
	PortfolioService_ListInstruments_FullMethodName             = "/portfolio.v1.PortfolioService/ListInstruments"
	PortfolioService_GetPortfolioHistory_FullMethodName         = "/portfolio.v1.PortfolioService/GetPortfolioHistory"
	PortfolioService_ListTransactions_FullMethodName            = "/portfolio.v1.PortfolioService/ListTransactions"
	PortfolioService_DeleteTransaction_FullMethodName           = "/portfolio.v1.PortfolioService/DeleteTransaction"
	PortfolioService_CheckTransactionDuplicates_FullMethodName  = "/portfolio.v1.PortfolioService/CheckTransactionDuplicates"
	PortfolioService_BatchImportTransactions_FullMethodName     = "/portfolio.v1.PortfolioService/BatchImportTransactions"
	PortfolioService_ListAllInstruments_FullMethodName          = "/portfolio.v1.PortfolioService/ListAllInstruments"
	PortfolioService_CreateInstrument_FullMethodName            = "/portfolio.v1.PortfolioService/CreateInstrument"
	PortfolioService_UpdateInstrument_FullMethodName            = "/portfolio.v1.PortfolioService/UpdateInstrument"
	PortfolioService_DeleteInstrument_FullMethodName            = "/portfolio.v1.PortfolioService/DeleteInstrument"
	PortfolioService_ListExchanges_FullMethodName               = "/portfolio.v1.PortfolioService/ListExchanges"
	PortfolioService_ListInstrumentPrices_FullMethodName        = "/portfolio.v1.PortfolioService/ListInstrumentPrices"
	PortfolioService_RecordPriceOverride_FullMethodName         = "/portfolio.v1.PortfolioService/RecordPriceOverride"
	PortfolioService_GetIngestionStatus_FullMethodName          = "/portfolio.v1.PortfolioService/GetIngestionStatus"
	PortfolioService_TriggerMarketSync_FullMethodName           = "/portfolio.v1.PortfolioService/TriggerMarketSync"
	PortfolioService_ListCurrencyPairs_FullMethodName           = "/portfolio.v1.PortfolioService/ListCurrencyPairs"
	PortfolioService_ListFXRates_FullMethodName                 = "/portfolio.v1.PortfolioService/ListFXRates"
	PortfolioService_GetCurrencyPairHistory_FullMethodName      = "/portfolio.v1.PortfolioService/GetCurrencyPairHistory"
	PortfolioService_RecordFXRateOverride_FullMethodName        = "/portfolio.v1.PortfolioService/RecordFXRateOverride"
	PortfolioService_TriggerBackfill_FullMethodName             = "/portfolio.v1.PortfolioService/TriggerBackfill"
	PortfolioService_RebuildValuations_FullMethodName           = "/portfolio.v1.PortfolioService/RebuildValuations"
	PortfolioService_GetCashFlowReport_FullMethodName           = "/portfolio.v1.PortfolioService/GetCashFlowReport"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*GetPortfolioResponse, error)
	UpdatePortfolioBaseCurrency(ctx context.Context, in *UpdatePortfolioBaseCurrencyRequest, opts ...grpc.CallOption) (*UpdatePortfolioBaseCurrencyResponse, error)
	AddTransaction(ctx context.Context, in *AddTransactionRequest, opts ...grpc.CallOption) (*AddTransactionResponse, error)
	ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error)
	GetPortfolioHistory(ctx context.Context, in *GetPortfolioHistoryRequest, opts ...grpc.CallOption) (*GetPortfolioHistoryResponse, error)
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*DeleteTransactionResponse, error)
	// Multi-Broker CSV Ingestion & Deduplication
	CheckTransactionDuplicates(ctx context.Context, in *CheckTransactionDuplicatesRequest, opts ...grpc.CallOption) (*CheckTransactionDuplicatesResponse, error)
	BatchImportTransactions(ctx context.Context, in *BatchImportTransactionsRequest, opts ...grpc.CallOption) (*BatchImportTransactionsResponse, error)
	// Admin: Asset Directory Management
	ListAllInstruments(ctx context.Context, in *ListAllInstrumentsRequest, opts ...grpc.CallOption) (*ListAllInstrumentsResponse, error)
	CreateInstrument(ctx context.Context, in *CreateInstrumentRequest, opts ...grpc.CallOption) (*CreateInstrumentResponse, error)
	UpdateInstrument(ctx context.Context, in *UpdateInstrumentRequest, opts ...grpc.CallOption) (*UpdateInstrumentResponse, error)
	DeleteInstrument(ctx context.Context, in *DeleteInstrumentRequest, opts ...grpc.CallOption) (*DeleteInstrumentResponse, error)
	ListExchanges(ctx context.Context, in *ListExchangesRequest, opts ...grpc.CallOption) (*ListExchangesResponse, error)
	// Admin: Closing Price Management & Overrides
	ListInstrumentPrices(ctx context.Context, in *ListInstrumentPricesRequest, opts ...grpc.CallOption) (*ListInstrumentPricesResponse, error)
	RecordPriceOverride(ctx context.Context, in *RecordPriceOverrideRequest, opts ...grpc.CallOption) (*RecordPriceOverrideResponse, error)
	// Admin: Ingestion Pipeline & Diagnostics
	GetIngestionStatus(ctx context.Context, in *GetIngestionStatusRequest, opts ...grpc.CallOption) (*GetIngestionStatusResponse, error)
	TriggerMarketSync(ctx context.Context, in *TriggerMarketSyncRequest, opts ...grpc.CallOption) (*TriggerMarketSyncResponse, error)
	// Admin: FX Rates & Currency Pair Inspection
	ListCurrencyPairs(ctx context.Context, in *ListCurrencyPairsRequest, opts ...grpc.CallOption) (*ListCurrencyPairsResponse, error)
	ListFXRates(ctx context.Context, in *ListFXRatesRequest, opts ...grpc.CallOption) (*ListFXRatesResponse, error)
	GetCurrencyPairHistory(ctx context.Context, in *GetCurrencyPairHistoryRequest, opts ...grpc.CallOption) (*GetCurrencyPairHistoryResponse, error)
	RecordFXRateOverride(ctx context.Context, in *RecordFXRateOverrideRequest, opts ...grpc.CallOption) (*RecordFXRateOverrideResponse, error)
	// Admin: Historical Market Data Backfill
	TriggerBackfill(ctx context.Context, in *TriggerBackfillRequest, opts ...grpc.CallOption) (*TriggerBackfillResponse, error)
	// Historical Valuation Engine & Replay
	RebuildValuations(ctx context.Context, in *RebuildValuationsRequest, opts ...grpc.CallOption) (*RebuildValuationsResponse, error)
	// Portfolio Cash Flow Report
	GetCashFlowReport(ctx context.Context, in *GetCashFlowReportRequest, opts ...grpc.CallOption) (*GetCashFlowReportResponse, error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*GetPortfolioResponse, error) {
	out := new(GetPortfolioResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetPortfolio_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) UpdatePortfolioBaseCurrency(ctx context.Context, in *UpdatePortfolioBaseCurrencyRequest, opts ...grpc.CallOption) (*UpdatePortfolioBaseCurrencyResponse, error) {
	out := new(UpdatePortfolioBaseCurrencyResponse)
	err := c.cc.Invoke(ctx, PortfolioService_UpdatePortfolioBaseCurrency_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) AddTransaction(ctx context.Context, in *AddTransactionRequest, opts ...grpc.CallOption) (*AddTransactionResponse, error) {
	out := new(AddTransactionResponse)
	err := c.cc.Invoke(ctx, PortfolioService_AddTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error) {
	out := new(ListInstrumentsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListInstruments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetPortfolioHistory(ctx context.Context, in *GetPortfolioHistoryRequest, opts ...grpc.CallOption) (*GetPortfolioHistoryResponse, error) {
	out := new(GetPortfolioHistoryResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetPortfolioHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*DeleteTransactionResponse, error) {
	out := new(DeleteTransactionResponse)
	err := c.cc.Invoke(ctx, PortfolioService_DeleteTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CheckTransactionDuplicates(ctx context.Context, in *CheckTransactionDuplicatesRequest, opts ...grpc.CallOption) (*CheckTransactionDuplicatesResponse, error) {
	out := new(CheckTransactionDuplicatesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CheckTransactionDuplicates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) BatchImportTransactions(ctx context.Context, in *BatchImportTransactionsRequest, opts ...grpc.CallOption) (*BatchImportTransactionsResponse, error) {
	out := new(BatchImportTransactionsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_BatchImportTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListAllInstruments(ctx context.Context, in *ListAllInstrumentsRequest, opts ...grpc.CallOption) (*ListAllInstrumentsResponse, error) {
	out := new(ListAllInstrumentsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListAllInstruments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateInstrument(ctx context.Context, in *CreateInstrumentRequest, opts ...grpc.CallOption) (*CreateInstrumentResponse, error) {
	out := new(CreateInstrumentResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CreateInstrument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) UpdateInstrument(ctx context.Context, in *UpdateInstrumentRequest, opts ...grpc.CallOption) (*UpdateInstrumentResponse, error) {
	out := new(UpdateInstrumentResponse)
	err := c.cc.Invoke(ctx, PortfolioService_UpdateInstrument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) DeleteInstrument(ctx context.Context, in *DeleteInstrumentRequest, opts ...grpc.CallOption) (*DeleteInstrumentResponse, error) {
	out := new(DeleteInstrumentResponse)
	err := c.cc.Invoke(ctx, PortfolioService_DeleteInstrument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListExchanges(ctx context.Context, in *ListExchangesRequest, opts ...grpc.CallOption) (*ListExchangesResponse, error) {
	out := new(ListExchangesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListExchanges_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListInstrumentPrices(ctx context.Context, in *ListInstrumentPricesRequest, opts ...grpc.CallOption) (*ListInstrumentPricesResponse, error) {
	out := new(ListInstrumentPricesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListInstrumentPrices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) RecordPriceOverride(ctx context.Context, in *RecordPriceOverrideRequest, opts ...grpc.CallOption) (*RecordPriceOverrideResponse, error) {
	out := new(RecordPriceOverrideResponse)
	err := c.cc.Invoke(ctx, PortfolioService_RecordPriceOverride_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetIngestionStatus(ctx context.Context, in *GetIngestionStatusRequest, opts ...grpc.CallOption) (*GetIngestionStatusResponse, error) {
	out := new(GetIngestionStatusResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetIngestionStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) TriggerMarketSync(ctx context.Context, in *TriggerMarketSyncRequest, opts ...grpc.CallOption) (*TriggerMarketSyncResponse, error) {
	out := new(TriggerMarketSyncResponse)
	err := c.cc.Invoke(ctx, PortfolioService_TriggerMarketSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListCurrencyPairs(ctx context.Context, in *ListCurrencyPairsRequest, opts ...grpc.CallOption) (*ListCurrencyPairsResponse, error) {
	out := new(ListCurrencyPairsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListCurrencyPairs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListFXRates(ctx context.Context, in *ListFXRatesRequest, opts ...grpc.CallOption) (*ListFXRatesResponse, error) {
	out := new(ListFXRatesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListFXRates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetCurrencyPairHistory(ctx context.Context, in *GetCurrencyPairHistoryRequest, opts ...grpc.CallOption) (*GetCurrencyPairHistoryResponse, error) {
	out := new(GetCurrencyPairHistoryResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetCurrencyPairHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) RecordFXRateOverride(ctx context.Context, in *RecordFXRateOverrideRequest, opts ...grpc.CallOption) (*RecordFXRateOverrideResponse, error) {
	out := new(RecordFXRateOverrideResponse)
	err := c.cc.Invoke(ctx, PortfolioService_RecordFXRateOverride_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) TriggerBackfill(ctx context.Context, in *TriggerBackfillRequest, opts ...grpc.CallOption) (*TriggerBackfillResponse, error) {
	out := new(TriggerBackfillResponse)
	err := c.cc.Invoke(ctx, PortfolioService_TriggerBackfill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) RebuildValuations(ctx context.Context, in *RebuildValuationsRequest, opts ...grpc.CallOption) (*RebuildValuationsResponse, error) {
	out := new(RebuildValuationsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_RebuildValuations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetCashFlowReport(ctx context.Context, in *GetCashFlowReportRequest, opts ...grpc.CallOption) (*GetCashFlowReportResponse, error) {
	out := new(GetCashFlowReportResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetCashFlowReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations must embed UnimplementedPortfolioServiceServer
// for forward compatibility
type PortfolioServiceServer interface {
	GetPortfolio(context.Context, *GetPortfolioRequest) (*GetPortfolioResponse, error)
	UpdatePortfolioBaseCurrency(context.Context, *UpdatePortfolioBaseCurrencyRequest) (*UpdatePortfolioBaseCurrencyResponse, error)
	AddTransaction(context.Context, *AddTransactionRequest) (*AddTransactionResponse, error)
	ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error)
	GetPortfolioHistory(context.Context, *GetPortfolioHistoryRequest) (*GetPortfolioHistoryResponse, error)
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	DeleteTransaction(context.Context, *DeleteTransactionRequest) (*DeleteTransactionResponse, error)
	// Multi-Broker CSV Ingestion & Deduplication
	CheckTransactionDuplicates(context.Context, *CheckTransactionDuplicatesRequest) (*CheckTransactionDuplicatesResponse, error)
	BatchImportTransactions(context.Context, *BatchImportTransactionsRequest) (*BatchImportTransactionsResponse, error)
	// Admin: Asset Directory Management
	ListAllInstruments(context.Context, *ListAllInstrumentsRequest) (*ListAllInstrumentsResponse, error)
	CreateInstrument(context.Context, *CreateInstrumentRequest) (*CreateInstrumentResponse, error)
	UpdateInstrument(context.Context, *UpdateInstrumentRequest) (*UpdateInstrumentResponse, error)
	DeleteInstrument(context.Context, *DeleteInstrumentRequest) (*DeleteInstrumentResponse, error)
	ListExchanges(context.Context, *ListExchangesRequest) (*ListExchangesResponse, error)
	// Admin: Closing Price Management & Overrides
	ListInstrumentPrices(context.Context, *ListInstrumentPricesRequest) (*ListInstrumentPricesResponse, error)
	RecordPriceOverride(context.Context, *RecordPriceOverrideRequest) (*RecordPriceOverrideResponse, error)
	// Admin: Ingestion Pipeline & Diagnostics
	GetIngestionStatus(context.Context, *GetIngestionStatusRequest) (*GetIngestionStatusResponse, error)
	TriggerMarketSync(context.Context, *TriggerMarketSyncRequest) (*TriggerMarketSyncResponse, error)
	// Admin: FX Rates & Currency Pair Inspection
	ListCurrencyPairs(context.Context, *ListCurrencyPairsRequest) (*ListCurrencyPairsResponse, error)
	ListFXRates(context.Context, *ListFXRatesRequest) (*ListFXRatesResponse, error)
	GetCurrencyPairHistory(context.Context, *GetCurrencyPairHistoryRequest) (*GetCurrencyPairHistoryResponse, error)
	RecordFXRateOverride(context.Context, *RecordFXRateOverrideRequest) (*RecordFXRateOverrideResponse, error)
	// Admin: Historical Market Data Backfill
	TriggerBackfill(context.Context, *TriggerBackfillRequest) (*TriggerBackfillResponse, error)
	// Historical Valuation Engine & Replay
	RebuildValuations(context.Context, *RebuildValuationsRequest) (*RebuildValuationsResponse, error)
	// Portfolio Cash Flow Report
	GetCashFlowReport(context.Context, *GetCashFlowReportRequest) (*GetCashFlowReportResponse, error)
	mustEmbedUnimplementedPortfolioServiceServer()
}

// UnimplementedPortfolioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortfolioServiceServer struct {
}

func (UnimplementedPortfolioServiceServer) GetPortfolio(context.Context, *GetPortfolioRequest) (*GetPortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (UnimplementedPortfolioServiceServer) UpdatePortfolioBaseCurrency(context.Context, *UpdatePortfolioBaseCurrencyRequest) (*UpdatePortfolioBaseCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePortfolioBaseCurrency not implemented")
}
func (UnimplementedPortfolioServiceServer) AddTransaction(context.Context, *AddTransactionRequest) (*AddTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTransaction not implemented")
}
func (UnimplementedPortfolioServiceServer) ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstruments not implemented")
}
func (UnimplementedPortfolioServiceServer) GetPortfolioHistory(context.Context, *GetPortfolioHistoryRequest) (*GetPortfolioHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolioHistory not implemented")
}
func (UnimplementedPortfolioServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedPortfolioServiceServer) DeleteTransaction(context.Context, *DeleteTransactionRequest) (*DeleteTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTransaction not implemented")
}
func (UnimplementedPortfolioServiceServer) CheckTransactionDuplicates(context.Context, *CheckTransactionDuplicatesRequest) (*CheckTransactionDuplicatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransactionDuplicates not implemented")
}
func (UnimplementedPortfolioServiceServer) BatchImportTransactions(context.Context, *BatchImportTransactionsRequest) (*BatchImportTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchImportTransactions not implemented")
}
func (UnimplementedPortfolioServiceServer) ListAllInstruments(context.Context, *ListAllInstrumentsRequest) (*ListAllInstrumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllInstruments not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateInstrument(context.Context, *CreateInstrumentRequest) (*CreateInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstrument not implemented")
}
func (UnimplementedPortfolioServiceServer) UpdateInstrument(context.Context, *UpdateInstrumentRequest) (*UpdateInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInstrument not implemented")
}
func (UnimplementedPortfolioServiceServer) DeleteInstrument(context.Context, *DeleteInstrumentRequest) (*DeleteInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInstrument not implemented")
}
func (UnimplementedPortfolioServiceServer) ListExchanges(context.Context, *ListExchangesRequest) (*ListExchangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExchanges not implemented")
}
func (UnimplementedPortfolioServiceServer) ListInstrumentPrices(context.Context, *ListInstrumentPricesRequest) (*ListInstrumentPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstrumentPrices not implemented")
}
func (UnimplementedPortfolioServiceServer) RecordPriceOverride(context.Context, *RecordPriceOverrideRequest) (*RecordPriceOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordPriceOverride not implemented")
}
func (UnimplementedPortfolioServiceServer) GetIngestionStatus(context.Context, *GetIngestionStatusRequest) (*GetIngestionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIngestionStatus not implemented")
}
func (UnimplementedPortfolioServiceServer) TriggerMarketSync(context.Context, *TriggerMarketSyncRequest) (*TriggerMarketSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerMarketSync not implemented")
}
func (UnimplementedPortfolioServiceServer) ListCurrencyPairs(context.Context, *ListCurrencyPairsRequest) (*ListCurrencyPairsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCurrencyPairs not implemented")
}
func (UnimplementedPortfolioServiceServer) ListFXRates(context.Context, *ListFXRatesRequest) (*ListFXRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFXRates not implemented")
}
func (UnimplementedPortfolioServiceServer) GetCurrencyPairHistory(context.Context, *GetCurrencyPairHistoryRequest) (*GetCurrencyPairHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencyPairHistory not implemented")
}
func (UnimplementedPortfolioServiceServer) RecordFXRateOverride(context.Context, *RecordFXRateOverrideRequest) (*RecordFXRateOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordFXRateOverride not implemented")
}
func (UnimplementedPortfolioServiceServer) TriggerBackfill(context.Context, *TriggerBackfillRequest) (*TriggerBackfillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerBackfill not implemented")
}
func (UnimplementedPortfolioServiceServer) RebuildValuations(context.Context, *RebuildValuationsRequest) (*RebuildValuationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildValuations not implemented")
}
func (UnimplementedPortfolioServiceServer) GetCashFlowReport(context.Context, *GetCashFlowReportRequest) (*GetCashFlowReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCashFlowReport not implemented")
}
func (UnimplementedPortfolioServiceServer) mustEmbedUnimplementedPortfolioServiceServer() {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, req.(*GetPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_UpdatePortfolioBaseCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePortfolioBaseCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).UpdatePortfolioBaseCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_UpdatePortfolioBaseCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).UpdatePortfolioBaseCurrency(ctx, req.(*UpdatePortfolioBaseCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_AddTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_AddTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddTransaction(ctx, req.(*AddTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstrumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListInstruments(ctx, req.(*ListInstrumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetPortfolioHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPortfolioHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetPortfolioHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPortfolioHistory(ctx, req.(*GetPortfolioHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_DeleteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).DeleteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_DeleteTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).DeleteTransaction(ctx, req.(*DeleteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CheckTransactionDuplicates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTransactionDuplicatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CheckTransactionDuplicates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CheckTransactionDuplicates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CheckTransactionDuplicates(ctx, req.(*CheckTransactionDuplicatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_BatchImportTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchImportTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).BatchImportTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_BatchImportTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).BatchImportTransactions(ctx, req.(*BatchImportTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListAllInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllInstrumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListAllInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListAllInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListAllInstruments(ctx, req.(*ListAllInstrumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateInstrument(ctx, req.(*CreateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_UpdateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).UpdateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_UpdateInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).UpdateInstrument(ctx, req.(*UpdateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_DeleteInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).DeleteInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_DeleteInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).DeleteInstrument(ctx, req.(*DeleteInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListExchanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListExchanges(ctx, req.(*ListExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListInstrumentPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstrumentPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListInstrumentPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListInstrumentPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListInstrumentPrices(ctx, req.(*ListInstrumentPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_RecordPriceOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPriceOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).RecordPriceOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_RecordPriceOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).RecordPriceOverride(ctx, req.(*RecordPriceOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetIngestionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngestionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetIngestionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetIngestionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetIngestionStatus(ctx, req.(*GetIngestionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_TriggerMarketSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerMarketSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).TriggerMarketSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_TriggerMarketSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).TriggerMarketSync(ctx, req.(*TriggerMarketSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListCurrencyPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrencyPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListCurrencyPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListCurrencyPairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListCurrencyPairs(ctx, req.(*ListCurrencyPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListFXRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFXRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListFXRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListFXRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListFXRates(ctx, req.(*ListFXRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetCurrencyPairHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyPairHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetCurrencyPairHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetCurrencyPairHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetCurrencyPairHistory(ctx, req.(*GetCurrencyPairHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_RecordFXRateOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordFXRateOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).RecordFXRateOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_RecordFXRateOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).RecordFXRateOverride(ctx, req.(*RecordFXRateOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_TriggerBackfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerBackfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).TriggerBackfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_TriggerBackfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).TriggerBackfill(ctx, req.(*TriggerBackfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_RebuildValuations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildValuationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).RebuildValuations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_RebuildValuations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).RebuildValuations(ctx, req.(*RebuildValuationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetCashFlowReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCashFlowReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetCashFlowReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetCashFlowReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetCashFlowReport(ctx, req.(*GetCashFlowReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portfolio.v1.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortfolio",
			Handler:    _PortfolioService_GetPortfolio_Handler,
		},
		{
			MethodName: "UpdatePortfolioBaseCurrency",
			Handler:    _PortfolioService_UpdatePortfolioBaseCurrency_Handler,
		},
		{
			MethodName: "AddTransaction",
			Handler:    _PortfolioService_AddTransaction_Handler,
		},
		{
			MethodName: "ListInstruments",
			Handler:    _PortfolioService_ListInstruments_Handler,
		},
		{
			MethodName: "GetPortfolioHistory",
			Handler:    _PortfolioService_GetPortfolioHistory_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _PortfolioService_ListTransactions_Handler,
		},
		{
			MethodName: "DeleteTransaction",
			Handler:    _PortfolioService_DeleteTransaction_Handler,
		},
		{
			MethodName: "CheckTransactionDuplicates",
			Handler:    _PortfolioService_CheckTransactionDuplicates_Handler,
		},
		{
			MethodName: "BatchImportTransactions",
			Handler:    _PortfolioService_BatchImportTransactions_Handler,
		},
		{
			MethodName: "ListAllInstruments",
			Handler:    _PortfolioService_ListAllInstruments_Handler,
		},
		{
			MethodName: "CreateInstrument",
			Handler:    _PortfolioService_CreateInstrument_Handler,
		},
		{
			MethodName: "UpdateInstrument",
			Handler:    _PortfolioService_UpdateInstrument_Handler,
		},
		{
			MethodName: "DeleteInstrument",
			Handler:    _PortfolioService_DeleteInstrument_Handler,
		},
		{
			MethodName: "ListExchanges",
			Handler:    _PortfolioService_ListExchanges_Handler,
		},
		{
			MethodName: "ListInstrumentPrices",
			Handler:    _PortfolioService_ListInstrumentPrices_Handler,
		},
		{
			MethodName: "RecordPriceOverride",
			Handler:    _PortfolioService_RecordPriceOverride_Handler,
		},
		{
			MethodName: "GetIngestionStatus",
			Handler:    _PortfolioService_GetIngestionStatus_Handler,
		},
		{
			MethodName: "TriggerMarketSync",
			Handler:    _PortfolioService_TriggerMarketSync_Handler,
		},
		{
			MethodName: "ListCurrencyPairs",
			Handler:    _PortfolioService_ListCurrencyPairs_Handler,
		},
		{
			MethodName: "ListFXRates",
			Handler:    _PortfolioService_ListFXRates_Handler,
		},
		{
			MethodName: "GetCurrencyPairHistory",
			Handler:    _PortfolioService_GetCurrencyPairHistory_Handler,
		},
		{
			MethodName: "RecordFXRateOverride",
			Handler:    _PortfolioService_RecordFXRateOverride_Handler,
		},
		{
			MethodName: "TriggerBackfill",
			Handler:    _PortfolioService_TriggerBackfill_Handler,
		},
		{
			MethodName: "RebuildValuations",
			Handler:    _PortfolioService_RebuildValuations_Handler,
		},
		{
			MethodName: "GetCashFlowReport",
			Handler:    _PortfolioService_GetCashFlowReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portfolio/v1/portfolio.proto",
}
