package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"bff/graph/model"
	"context"
	pb "graphfolio/proto/portfolio/v1"
)

// AddTransaction is the resolver for the addTransaction field.
func (r *mutationResolver) AddTransaction(ctx context.Context, input model.AddTransactionInput) (*model.AddTransactionPayload, error) {
	currency := "USD"
	if input.CurrencyCode != nil && *input.CurrencyCode != "" {
		currency = *input.CurrencyCode
	}

	req := &pb.AddTransactionRequest{
		UserId:    "1", // Default user ID for single-user/demo session
		Type:      toProtoTransactionType(input.Type),
		TradeDate: input.TradeDate,
		Quantity:  toProtoDecimal(input.Quantity),
		Price:     toProtoMoney(input.Price, currency),
		Amount:    toProtoMoney(input.Amount, currency),
		Fee:       toProtoMoney(input.Fee, currency),
	}

	if input.Symbol != nil {
		req.Symbol = *input.Symbol
	}
	if input.Notes != nil {
		req.Notes = *input.Notes
	}

	resp, err := r.PortfolioClient.AddTransaction(ctx, req)
	if err != nil {
		return nil, err
	}

	return &model.AddTransactionPayload{
		TransactionID: resp.TransactionId,
		Portfolio:     toModelPortfolio(resp.Portfolio),
	}, nil
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context) (*model.Portfolio, error) {
	resp, err := r.PortfolioClient.GetPortfolio(ctx, &pb.GetPortfolioRequest{
		UserId: "1", // Hardcoded for single-user/demo session
	})
	if err != nil {
		return nil, err
	}

	return toModelPortfolio(resp.Portfolio), nil
}

// Instruments is the resolver for the instruments field.
func (r *queryResolver) Instruments(ctx context.Context) ([]*model.Instrument, error) {
	resp, err := r.PortfolioClient.ListInstruments(ctx, &pb.ListInstrumentsRequest{})
	if err != nil {
		return nil, err
	}

	instruments := make([]*model.Instrument, len(resp.Instruments))
	for i, inst := range resp.Instruments {
		instruments[i] = &model.Instrument{
			ID:           inst.Id,
			Symbol:       inst.Symbol,
			Name:         inst.Name,
			CurrencyCode: inst.CurrencyCode,
			AssetClass:   inst.AssetClass,
		}
	}

	return instruments, nil
}

// PortfolioHistory is the resolver for the portfolioHistory field.
func (r *queryResolver) PortfolioHistory(ctx context.Context, timeframe model.HistoryTimeframe) (*model.PortfolioHistory, error) {
	resp, err := r.PortfolioClient.GetPortfolioHistory(ctx, &pb.GetPortfolioHistoryRequest{
		UserId:    "1", // Hardcoded for single-user/demo session
		Timeframe: toProtoHistoryTimeframe(timeframe),
	})
	if err != nil {
		return nil, err
	}

	return toModelPortfolioHistory(resp), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
