package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	
	"bff/graph/model"
	pb "graphfolio/proto/portfolio/v1"
)

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context) (*model.Portfolio, error) {
	resp, err := r.PortfolioClient.GetPortfolio(ctx, &pb.GetPortfolioRequest{
		UserId: "1", // Hardcoded for now
	})
	if err != nil {
		return nil, err
	}

	investments := make([]*model.Investment, len(resp.Portfolio.Investments))
	for i, inv := range resp.Portfolio.Investments {
		investments[i] = &model.Investment{
			ID:                 inv.Id,
			Ticker:             inv.Ticker,
			Name:               inv.Name,
			Price:              inv.Price,
			Quantity:           inv.Quantity,
			TotalValue:         inv.TotalValue,
			TodayReturnAmount:  inv.TodayReturnAmount,
			TodayReturnPercent: inv.TodayReturnPercent,
			TotalReturnAmount:  inv.TotalReturnAmount,
			TotalReturnPercent: inv.TotalReturnPercent,
		}
	}

	return &model.Portfolio{
		TotalValue:              resp.Portfolio.TotalValue,
		TodayReturnAmount:       resp.Portfolio.TodayReturnAmount,
		TodayReturnPercent:      resp.Portfolio.TodayReturnPercent,
		AnnualizedReturnPercent: resp.Portfolio.AnnualizedReturnPercent,
		CashBalance:             resp.Portfolio.CashBalance,
		Investments:             investments,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
