package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"bff/graph/model"
	"context"
	pb "graphfolio/proto/portfolio/v1"
)

// AddTransaction is the resolver for the addTransaction field.
func (r *mutationResolver) AddTransaction(ctx context.Context, input model.AddTransactionInput) (*model.AddTransactionPayload, error) {
	currency := "USD"
	if input.CurrencyCode != nil && *input.CurrencyCode != "" {
		currency = *input.CurrencyCode
	}

	req := &pb.AddTransactionRequest{
		UserId:    "1", // Default user ID for single-user/demo session
		Type:      toProtoTransactionType(input.Type),
		TradeDate: input.TradeDate,
		Quantity:  toProtoDecimal(input.Quantity),
		Price:     toProtoMoney(input.Price, currency),
		Amount:    toProtoMoney(input.Amount, currency),
		Fee:       toProtoMoney(input.Fee, currency),
	}

	if input.Symbol != nil {
		req.Symbol = *input.Symbol
	}
	if input.Notes != nil {
		req.Notes = *input.Notes
	}

	resp, err := r.PortfolioClient.AddTransaction(ctx, req)
	if err != nil {
		return nil, err
	}

	return &model.AddTransactionPayload{
		TransactionID: resp.TransactionId,
		Portfolio:     toModelPortfolio(resp.Portfolio),
	}, nil
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id string) (*model.DeleteTransactionPayload, error) {
	resp, err := r.PortfolioClient.DeleteTransaction(ctx, &pb.DeleteTransactionRequest{
		UserId:        "1", // Hardcoded for single-user/demo session
		TransactionId: id,
	})
	if err != nil {
		return nil, err
	}

	return &model.DeleteTransactionPayload{
		Success:   resp.Success,
		Portfolio: toModelPortfolio(resp.Portfolio),
	}, nil
}

// CreateInstrument is the resolver for the createInstrument field.
func (r *mutationResolver) CreateInstrument(ctx context.Context, input model.CreateInstrumentInput) (*model.Instrument, error) {
	req := &pb.CreateInstrumentRequest{
		Symbol:       input.Symbol,
		ExchangeCode: input.ExchangeCode,
		Name:         input.Name,
		AssetClass:   input.AssetClass,
		CurrencyCode: input.CurrencyCode,
		Isin:         input.Isin,
	}

	resp, err := r.PortfolioClient.CreateInstrument(ctx, req)
	if err != nil {
		return nil, err
	}

	return toModelInstrument(resp.Instrument), nil
}

// UpdateInstrument is the resolver for the updateInstrument field.
func (r *mutationResolver) UpdateInstrument(ctx context.Context, input model.UpdateInstrumentInput) (*model.Instrument, error) {
	req := &pb.UpdateInstrumentRequest{
		Id:       input.ID,
		Name:     input.Name,
		IsActive: input.IsActive,
		Isin:     input.Isin,
	}

	resp, err := r.PortfolioClient.UpdateInstrument(ctx, req)
	if err != nil {
		return nil, err
	}

	return toModelInstrument(resp.Instrument), nil
}

// RecordPriceOverride is the resolver for the recordPriceOverride field.
func (r *mutationResolver) RecordPriceOverride(ctx context.Context, input model.RecordPriceOverrideInput) (*model.RecordPriceOverridePayload, error) {
	recompute := false
	if input.RecomputeValuations != nil {
		recompute = *input.RecomputeValuations
	}

	req := &pb.RecordPriceOverrideRequest{
		Symbol:              input.Symbol,
		PriceDate:           input.PriceDate,
		Price:               toProtoDecimal(&input.Price),
		Reason:              input.Reason,
		RecomputeValuations: recompute,
	}

	resp, err := r.PortfolioClient.RecordPriceOverride(ctx, req)
	if err != nil {
		return nil, err
	}

	return &model.RecordPriceOverridePayload{
		Price:                toModelInstrumentPrice(resp.Price),
		ValuationsRecomputed: resp.ValuationsRecomputed,
	}, nil
}

// TriggerMarketSync is the resolver for the triggerMarketSync field.
func (r *mutationResolver) TriggerMarketSync(ctx context.Context, symbols []string, syncFx *bool) (*model.MarketSyncPayload, error) {
	sync := false
	if syncFx != nil {
		sync = *syncFx
	}

	req := &pb.TriggerMarketSyncRequest{
		Symbols: symbols,
		SyncFx:  sync,
	}

	resp, err := r.PortfolioClient.TriggerMarketSync(ctx, req)
	if err != nil {
		return nil, err
	}

	return &model.MarketSyncPayload{
		Success:       resp.Success,
		PricesSynced:  int(resp.PricesSynced),
		FxRatesSynced: int(resp.FxRatesSynced),
		Message:       resp.Message,
	}, nil
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context) (*model.Portfolio, error) {
	resp, err := r.PortfolioClient.GetPortfolio(ctx, &pb.GetPortfolioRequest{
		UserId: "1", // Hardcoded for single-user/demo session
	})
	if err != nil {
		return nil, err
	}

	return toModelPortfolio(resp.Portfolio), nil
}

// Instruments is the resolver for the instruments field.
func (r *queryResolver) Instruments(ctx context.Context) ([]*model.Instrument, error) {
	resp, err := r.PortfolioClient.ListInstruments(ctx, &pb.ListInstrumentsRequest{})
	if err != nil {
		return nil, err
	}

	instruments := make([]*model.Instrument, len(resp.Instruments))
	for i, inst := range resp.Instruments {
		instruments[i] = toModelInstrument(inst)
	}

	return instruments, nil
}

// PortfolioHistory is the resolver for the portfolioHistory field.
func (r *queryResolver) PortfolioHistory(ctx context.Context, timeframe model.HistoryTimeframe) (*model.PortfolioHistory, error) {
	resp, err := r.PortfolioClient.GetPortfolioHistory(ctx, &pb.GetPortfolioHistoryRequest{
		UserId:    "1", // Hardcoded for single-user/demo session
		Timeframe: toProtoHistoryTimeframe(timeframe),
	})
	if err != nil {
		return nil, err
	}

	return toModelPortfolioHistory(resp), nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, typeArg *model.TransactionType, symbol *string, page *int, pageSize *int) (*model.TransactionsConnection, error) {
	req := &pb.ListTransactionsRequest{
		UserId: "1", // Hardcoded for single-user/demo session
	}

	if typeArg != nil {
		req.Type = toProtoTransactionType(*typeArg)
	}
	if symbol != nil {
		req.Symbol = *symbol
	}
	if page != nil {
		req.Page = int32(*page)
	}
	if pageSize != nil {
		req.PageSize = int32(*pageSize)
	}

	resp, err := r.PortfolioClient.ListTransactions(ctx, req)
	if err != nil {
		return nil, err
	}

	return toModelTransactionsConnection(resp), nil
}

// AllInstruments is the resolver for the allInstruments field.
func (r *queryResolver) AllInstruments(ctx context.Context, isActive *bool, search *string) ([]*model.Instrument, error) {
	req := &pb.ListAllInstrumentsRequest{
		IsActive: isActive,
		Search:   search,
	}

	resp, err := r.PortfolioClient.ListAllInstruments(ctx, req)
	if err != nil {
		return nil, err
	}

	instruments := make([]*model.Instrument, len(resp.Instruments))
	for i, inst := range resp.Instruments {
		instruments[i] = toModelInstrument(inst)
	}

	return instruments, nil
}

// InstrumentPrices is the resolver for the instrumentPrices field.
func (r *queryResolver) InstrumentPrices(ctx context.Context, symbol *string, fromDate *string, toDate *string, limit *int, offset *int) (*model.InstrumentPricesConnection, error) {
	req := &pb.ListInstrumentPricesRequest{
		Symbol:   symbol,
		FromDate: fromDate,
		ToDate:   toDate,
	}

	if limit != nil {
		req.Limit = int32(*limit)
	}
	if offset != nil {
		req.Offset = int32(*offset)
	}

	resp, err := r.PortfolioClient.ListInstrumentPrices(ctx, req)
	if err != nil {
		return nil, err
	}

	return toModelInstrumentPricesConnection(resp), nil
}

// IngestionStatus is the resolver for the ingestionStatus field.
func (r *queryResolver) IngestionStatus(ctx context.Context) (*model.IngestionStatus, error) {
	resp, err := r.PortfolioClient.GetIngestionStatus(ctx, &pb.GetIngestionStatusRequest{})
	if err != nil {
		return nil, err
	}

	return toModelIngestionStatus(resp), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
