// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Investment struct {
	ID                 string  `json:"id"`
	Ticker             string  `json:"ticker"`
	Name               string  `json:"name"`
	Price              *Money  `json:"price"`
	Quantity           Decimal `json:"quantity"`
	TotalValue         *Money  `json:"totalValue"`
	TodayReturnAmount  *Money  `json:"todayReturnAmount"`
	TodayReturnPercent Decimal `json:"todayReturnPercent"`
	TotalReturnAmount  *Money  `json:"totalReturnAmount"`
	TotalReturnPercent Decimal `json:"totalReturnPercent"`
}

type Money struct {
	Amount       Decimal `json:"amount"`
	CurrencyCode string  `json:"currencyCode"`
}

type Portfolio struct {
	TotalValue              *Money        `json:"totalValue"`
	TodayReturnAmount       *Money        `json:"todayReturnAmount"`
	TodayReturnPercent      Decimal       `json:"todayReturnPercent"`
	AnnualizedReturnPercent Decimal       `json:"annualizedReturnPercent"`
	CashBalance             *Money        `json:"cashBalance"`
	Investments             []*Investment `json:"investments"`
}

type Query struct {
}
