// Code generated by MockGen. DO NOT EDIT.
// Source: portfolio-api/internal/service (interfaces: IngestionService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_ingestion_service.go -package=mocks portfolio-api/internal/service IngestionService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "portfolio-api/internal/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIngestionService is a mock of IngestionService interface.
type MockIngestionService struct {
	ctrl     *gomock.Controller
	recorder *MockIngestionServiceMockRecorder
	isgomock struct{}
}

// MockIngestionServiceMockRecorder is the mock recorder for MockIngestionService.
type MockIngestionServiceMockRecorder struct {
	mock *MockIngestionService
}

// NewMockIngestionService creates a new mock instance.
func NewMockIngestionService(ctrl *gomock.Controller) *MockIngestionService {
	mock := &MockIngestionService{ctrl: ctrl}
	mock.recorder = &MockIngestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestionService) EXPECT() *MockIngestionServiceMockRecorder {
	return m.recorder
}

// BackfillCurrencyPair mocks base method.
func (m *MockIngestionService) BackfillCurrencyPair(ctx context.Context, base, quote string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillCurrencyPair", ctx, base, quote, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackfillCurrencyPair indicates an expected call of BackfillCurrencyPair.
func (mr *MockIngestionServiceMockRecorder) BackfillCurrencyPair(ctx, base, quote, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillCurrencyPair", reflect.TypeOf((*MockIngestionService)(nil).BackfillCurrencyPair), ctx, base, quote, fromDate, toDate)
}

// BackfillInstrumentPrices mocks base method.
func (m *MockIngestionService) BackfillInstrumentPrices(ctx context.Context, instrumentID uuid.UUID, symbol, exchange string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillInstrumentPrices", ctx, instrumentID, symbol, exchange, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackfillInstrumentPrices indicates an expected call of BackfillInstrumentPrices.
func (mr *MockIngestionServiceMockRecorder) BackfillInstrumentPrices(ctx, instrumentID, symbol, exchange, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillInstrumentPrices", reflect.TypeOf((*MockIngestionService)(nil).BackfillInstrumentPrices), ctx, instrumentID, symbol, exchange, fromDate, toDate)
}

// IngestDailyMarketData mocks base method.
func (m *MockIngestionService) IngestDailyMarketData(ctx context.Context, asOfDate time.Time) (*domain.MarketSyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestDailyMarketData", ctx, asOfDate)
	ret0, _ := ret[0].(*domain.MarketSyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestDailyMarketData indicates an expected call of IngestDailyMarketData.
func (mr *MockIngestionServiceMockRecorder) IngestDailyMarketData(ctx, asOfDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestDailyMarketData", reflect.TypeOf((*MockIngestionService)(nil).IngestDailyMarketData), ctx, asOfDate)
}
