// Code generated by MockGen. DO NOT EDIT.
// Source: portfolio-api/internal/service (interfaces: PortfolioService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks portfolio-api/internal/service PortfolioService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "portfolio-api/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPortfolioService is a mock of PortfolioService interface.
type MockPortfolioService struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioServiceMockRecorder
	isgomock struct{}
}

// MockPortfolioServiceMockRecorder is the mock recorder for MockPortfolioService.
type MockPortfolioServiceMockRecorder struct {
	mock *MockPortfolioService
}

// NewMockPortfolioService creates a new mock instance.
func NewMockPortfolioService(ctrl *gomock.Controller) *MockPortfolioService {
	mock := &MockPortfolioService{ctrl: ctrl}
	mock.recorder = &MockPortfolioServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioService) EXPECT() *MockPortfolioServiceMockRecorder {
	return m.recorder
}

// AddTransaction mocks base method.
func (m *MockPortfolioService) AddTransaction(ctx context.Context, input domain.AddTransactionInput) (*domain.Transaction, *domain.PortfolioSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTransaction", ctx, input)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(*domain.PortfolioSummary)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddTransaction indicates an expected call of AddTransaction.
func (mr *MockPortfolioServiceMockRecorder) AddTransaction(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTransaction", reflect.TypeOf((*MockPortfolioService)(nil).AddTransaction), ctx, input)
}

// CreateInstrument mocks base method.
func (m *MockPortfolioService) CreateInstrument(ctx context.Context, input domain.CreateInstrumentInput) (*domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstrument", ctx, input)
	ret0, _ := ret[0].(*domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstrument indicates an expected call of CreateInstrument.
func (mr *MockPortfolioServiceMockRecorder) CreateInstrument(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstrument", reflect.TypeOf((*MockPortfolioService)(nil).CreateInstrument), ctx, input)
}

// DeleteTransaction mocks base method.
func (m *MockPortfolioService) DeleteTransaction(ctx context.Context, userID, transactionID string) (*domain.PortfolioSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", ctx, userID, transactionID)
	ret0, _ := ret[0].(*domain.PortfolioSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockPortfolioServiceMockRecorder) DeleteTransaction(ctx, userID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockPortfolioService)(nil).DeleteTransaction), ctx, userID, transactionID)
}

// GetIngestionStatus mocks base method.
func (m *MockPortfolioService) GetIngestionStatus(ctx context.Context) (*domain.IngestionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngestionStatus", ctx)
	ret0, _ := ret[0].(*domain.IngestionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIngestionStatus indicates an expected call of GetIngestionStatus.
func (mr *MockPortfolioServiceMockRecorder) GetIngestionStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngestionStatus", reflect.TypeOf((*MockPortfolioService)(nil).GetIngestionStatus), ctx)
}

// GetPortfolioHistory mocks base method.
func (m *MockPortfolioService) GetPortfolioHistory(ctx context.Context, userID string, timeframe domain.HistoryTimeframe) (*domain.PortfolioHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolioHistory", ctx, userID, timeframe)
	ret0, _ := ret[0].(*domain.PortfolioHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPortfolioHistory indicates an expected call of GetPortfolioHistory.
func (mr *MockPortfolioServiceMockRecorder) GetPortfolioHistory(ctx, userID, timeframe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolioHistory", reflect.TypeOf((*MockPortfolioService)(nil).GetPortfolioHistory), ctx, userID, timeframe)
}

// GetPortfolioSummary mocks base method.
func (m *MockPortfolioService) GetPortfolioSummary(ctx context.Context, userID string) (*domain.PortfolioSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolioSummary", ctx, userID)
	ret0, _ := ret[0].(*domain.PortfolioSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPortfolioSummary indicates an expected call of GetPortfolioSummary.
func (mr *MockPortfolioServiceMockRecorder) GetPortfolioSummary(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolioSummary", reflect.TypeOf((*MockPortfolioService)(nil).GetPortfolioSummary), ctx, userID)
}

// ListAllInstruments mocks base method.
func (m *MockPortfolioService) ListAllInstruments(ctx context.Context, isActive *bool, search *string) ([]domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllInstruments", ctx, isActive, search)
	ret0, _ := ret[0].([]domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllInstruments indicates an expected call of ListAllInstruments.
func (mr *MockPortfolioServiceMockRecorder) ListAllInstruments(ctx, isActive, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllInstruments", reflect.TypeOf((*MockPortfolioService)(nil).ListAllInstruments), ctx, isActive, search)
}

// ListInstrumentPrices mocks base method.
func (m *MockPortfolioService) ListInstrumentPrices(ctx context.Context, filter domain.PriceFilter) ([]domain.InstrumentPrice, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstrumentPrices", ctx, filter)
	ret0, _ := ret[0].([]domain.InstrumentPrice)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInstrumentPrices indicates an expected call of ListInstrumentPrices.
func (mr *MockPortfolioServiceMockRecorder) ListInstrumentPrices(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstrumentPrices", reflect.TypeOf((*MockPortfolioService)(nil).ListInstrumentPrices), ctx, filter)
}

// ListInstruments mocks base method.
func (m *MockPortfolioService) ListInstruments(ctx context.Context) ([]domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstruments", ctx)
	ret0, _ := ret[0].([]domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstruments indicates an expected call of ListInstruments.
func (mr *MockPortfolioServiceMockRecorder) ListInstruments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstruments", reflect.TypeOf((*MockPortfolioService)(nil).ListInstruments), ctx)
}

// ListTransactions mocks base method.
func (m *MockPortfolioService) ListTransactions(ctx context.Context, userID string, filter domain.TransactionFilter) ([]domain.TransactionWithInstrument, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, userID, filter)
	ret0, _ := ret[0].([]domain.TransactionWithInstrument)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockPortfolioServiceMockRecorder) ListTransactions(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockPortfolioService)(nil).ListTransactions), ctx, userID, filter)
}

// RebuildProjections mocks base method.
func (m *MockPortfolioService) RebuildProjections(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildProjections", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildProjections indicates an expected call of RebuildProjections.
func (mr *MockPortfolioServiceMockRecorder) RebuildProjections(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildProjections", reflect.TypeOf((*MockPortfolioService)(nil).RebuildProjections), ctx, userID)
}

// RecordPriceOverride mocks base method.
func (m *MockPortfolioService) RecordPriceOverride(ctx context.Context, input domain.PriceOverrideInput) (*domain.InstrumentPrice, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPriceOverride", ctx, input)
	ret0, _ := ret[0].(*domain.InstrumentPrice)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecordPriceOverride indicates an expected call of RecordPriceOverride.
func (mr *MockPortfolioServiceMockRecorder) RecordPriceOverride(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPriceOverride", reflect.TypeOf((*MockPortfolioService)(nil).RecordPriceOverride), ctx, input)
}

// TriggerMarketSync mocks base method.
func (m *MockPortfolioService) TriggerMarketSync(ctx context.Context, symbols []string, syncFX bool) (*domain.MarketSyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerMarketSync", ctx, symbols, syncFX)
	ret0, _ := ret[0].(*domain.MarketSyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerMarketSync indicates an expected call of TriggerMarketSync.
func (mr *MockPortfolioServiceMockRecorder) TriggerMarketSync(ctx, symbols, syncFX any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerMarketSync", reflect.TypeOf((*MockPortfolioService)(nil).TriggerMarketSync), ctx, symbols, syncFX)
}

// UpdateInstrument mocks base method.
func (m *MockPortfolioService) UpdateInstrument(ctx context.Context, input domain.UpdateInstrumentInput) (*domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstrument", ctx, input)
	ret0, _ := ret[0].(*domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstrument indicates an expected call of UpdateInstrument.
func (mr *MockPortfolioServiceMockRecorder) UpdateInstrument(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstrument", reflect.TypeOf((*MockPortfolioService)(nil).UpdateInstrument), ctx, input)
}
