// Code generated by MockGen. DO NOT EDIT.
// Source: portfolio-api/internal/service (interfaces: ValuationService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_valuation_service.go -package=mocks portfolio-api/internal/service ValuationService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "portfolio-api/internal/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockValuationService is a mock of ValuationService interface.
type MockValuationService struct {
	ctrl     *gomock.Controller
	recorder *MockValuationServiceMockRecorder
	isgomock struct{}
}

// MockValuationServiceMockRecorder is the mock recorder for MockValuationService.
type MockValuationServiceMockRecorder struct {
	mock *MockValuationService
}

// NewMockValuationService creates a new mock instance.
func NewMockValuationService(ctrl *gomock.Controller) *MockValuationService {
	mock := &MockValuationService{ctrl: ctrl}
	mock.recorder = &MockValuationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValuationService) EXPECT() *MockValuationServiceMockRecorder {
	return m.recorder
}

// BackfillPortfolioValuations mocks base method.
func (m *MockValuationService) BackfillPortfolioValuations(ctx context.Context, portfolioID uuid.UUID, fromDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillPortfolioValuations", ctx, portfolioID, fromDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackfillPortfolioValuations indicates an expected call of BackfillPortfolioValuations.
func (mr *MockValuationServiceMockRecorder) BackfillPortfolioValuations(ctx, portfolioID, fromDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillPortfolioValuations", reflect.TypeOf((*MockValuationService)(nil).BackfillPortfolioValuations), ctx, portfolioID, fromDate)
}

// RunDailyValuationJob mocks base method.
func (m *MockValuationService) RunDailyValuationJob(ctx context.Context, asOfDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunDailyValuationJob", ctx, asOfDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunDailyValuationJob indicates an expected call of RunDailyValuationJob.
func (mr *MockValuationServiceMockRecorder) RunDailyValuationJob(ctx, asOfDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunDailyValuationJob", reflect.TypeOf((*MockValuationService)(nil).RunDailyValuationJob), ctx, asOfDate)
}

// SnapshotValuation mocks base method.
func (m *MockValuationService) SnapshotValuation(ctx context.Context, portfolioID uuid.UUID, asOfDate time.Time) (*domain.PortfolioValuationSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotValuation", ctx, portfolioID, asOfDate)
	ret0, _ := ret[0].(*domain.PortfolioValuationSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnapshotValuation indicates an expected call of SnapshotValuation.
func (mr *MockValuationServiceMockRecorder) SnapshotValuation(ctx, portfolioID, asOfDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotValuation", reflect.TypeOf((*MockValuationService)(nil).SnapshotValuation), ctx, portfolioID, asOfDate)
}
