// Code generated by MockGen. DO NOT EDIT.
// Source: portfolio-api/internal/service (interfaces: PortfolioService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks portfolio-api/internal/service PortfolioService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "portfolio-api/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPortfolioService is a mock of PortfolioService interface.
type MockPortfolioService struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioServiceMockRecorder
	isgomock struct{}
}

// MockPortfolioServiceMockRecorder is the mock recorder for MockPortfolioService.
type MockPortfolioServiceMockRecorder struct {
	mock *MockPortfolioService
}

// NewMockPortfolioService creates a new mock instance.
func NewMockPortfolioService(ctrl *gomock.Controller) *MockPortfolioService {
	mock := &MockPortfolioService{ctrl: ctrl}
	mock.recorder = &MockPortfolioServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioService) EXPECT() *MockPortfolioServiceMockRecorder {
	return m.recorder
}

// AddTransaction mocks base method.
func (m *MockPortfolioService) AddTransaction(ctx context.Context, input domain.AddTransactionInput) (*domain.Transaction, *domain.PortfolioSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTransaction", ctx, input)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(*domain.PortfolioSummary)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddTransaction indicates an expected call of AddTransaction.
func (mr *MockPortfolioServiceMockRecorder) AddTransaction(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTransaction", reflect.TypeOf((*MockPortfolioService)(nil).AddTransaction), ctx, input)
}

// GetPortfolioSummary mocks base method.
func (m *MockPortfolioService) GetPortfolioSummary(ctx context.Context, userID string) (*domain.PortfolioSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolioSummary", ctx, userID)
	ret0, _ := ret[0].(*domain.PortfolioSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPortfolioSummary indicates an expected call of GetPortfolioSummary.
func (mr *MockPortfolioServiceMockRecorder) GetPortfolioSummary(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolioSummary", reflect.TypeOf((*MockPortfolioService)(nil).GetPortfolioSummary), ctx, userID)
}

// ListInstruments mocks base method.
func (m *MockPortfolioService) ListInstruments(ctx context.Context) ([]domain.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstruments", ctx)
	ret0, _ := ret[0].([]domain.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstruments indicates an expected call of ListInstruments.
func (mr *MockPortfolioServiceMockRecorder) ListInstruments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstruments", reflect.TypeOf((*MockPortfolioService)(nil).ListInstruments), ctx)
}

// RebuildProjections mocks base method.
func (m *MockPortfolioService) RebuildProjections(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildProjections", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildProjections indicates an expected call of RebuildProjections.
func (mr *MockPortfolioServiceMockRecorder) RebuildProjections(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildProjections", reflect.TypeOf((*MockPortfolioService)(nil).RebuildProjections), ctx, userID)
}
